package com.gimnasio.model;
// Generated ago 3, 2016 11:34:53 p.m. by Hibernate Tools 4.3.1

/**
 * ClientePaqueteDto generated by hbm2java
 */
public class ClientePaqueteDto implements java.io.Serializable {

    private Long id;

    private ClienteDto clienteDto;
    private DescuentoDto descuentoDto;
    private PaqueteDto paqueteDto;
    private UsuarioDto usuarioDto;

    private Long clienteId;
    private Long descuentoId;
    private Long paqueteId;
    private Long usuarioId;

    private short numeroDiasTiquetera;
    private short diasUsadosTiquetera;
    private double precioBase;
    private double valorTotal;
    private short estado;

    private String fechaIniciaPaquete;
    private String fechaFinalizaPaquete;
    private String fechaRegistro;
    private String fechaModificacion;

    public ClientePaqueteDto() {
        this.paqueteDto = new PaqueteDto();
        this.clienteDto = new ClienteDto();
        this.descuentoDto = new DescuentoDto();
        this.usuarioDto = new UsuarioDto();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ClienteDto getClienteDto() {
        return clienteDto;
    }

    public void setClienteDto(ClienteDto clienteDto) {
        this.clienteDto = clienteDto;
    }

    public DescuentoDto getDescuentoDto() {
        return descuentoDto;
    }

    public void setDescuentoDto(DescuentoDto descuentoDto) {
        this.descuentoDto = descuentoDto;
    }

    public PaqueteDto getPaqueteDto() {
        return paqueteDto;
    }

    public void setPaqueteDto(PaqueteDto paqueteDto) {
        this.paqueteDto = paqueteDto;
    }

    public UsuarioDto getUsuarioDto() {
        return usuarioDto;
    }

    public void setUsuarioDto(UsuarioDto usuarioDto) {
        this.usuarioDto = usuarioDto;
    }

    public Long getClienteId() {
        return clienteId;
    }

    public void setClienteId(Long clienteId) {
        this.clienteId = clienteId;
    }

    public Long getDescuentoId() {
        return descuentoId;
    }

    public void setDescuentoId(Long descuentoId) {
        this.descuentoId = descuentoId;
    }

    public Long getPaqueteId() {
        return paqueteId;
    }

    public void setPaqueteId(Long paqueteId) {
        this.paqueteId = paqueteId;
    }

    public Long getUsuarioId() {
        return usuarioId;
    }

    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }

    public double getValorTotal() {
        return valorTotal;
    }

    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }

    public String getFechaIniciaPaquete() {
        return fechaIniciaPaquete;
    }

    public void setFechaIniciaPaquete(String fechaIniciaPaquete) {
        this.fechaIniciaPaquete = fechaIniciaPaquete;
    }

    public String getFechaFinalizaPaquete() {
        return fechaFinalizaPaquete;
    }

    public void setFechaFinalizaPaquete(String fechaFinalizaPaquete) {
        this.fechaFinalizaPaquete = fechaFinalizaPaquete;
    }

    public String getFechaRegistro() {
        return fechaRegistro;
    }

    public void setFechaRegistro(String fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public String getFechaModificacion() {
        return fechaModificacion;
    }

    public void setFechaModificacion(String fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public short getNumeroDiasTiquetera() {
        return numeroDiasTiquetera;
    }

    public void setNumeroDiasTiquetera(short numeroDiasTiquetera) {
        this.numeroDiasTiquetera = numeroDiasTiquetera;
    }

    public short getDiasUsadosTiquetera() {
        return diasUsadosTiquetera;
    }

    public void setDiasUsadosTiquetera(short diasUsadosTiquetera) {
        this.diasUsadosTiquetera = diasUsadosTiquetera;
    }

    public double getPrecioBase() {
        return precioBase;
    }

    public void setPrecioBase(double precioBase) {
        this.precioBase = precioBase;
    }

    public short getEstado() {
        return estado;
    }

    public void setEstado(short estado) {
        this.estado = estado;
    }

}
