package com.gimnasio.model;
// Generated ago 3, 2016 11:34:53 p.m. by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PagoDto generated by hbm2java
 */
public class PagoDto implements java.io.Serializable {

    private Long id;
    private ClientePaqueteDto clientePaqueteDto;
    private UsuarioDto usuarioDto;
    private BigDecimal valor;
    private Date fechaPago;

    public PagoDto() {
        this.clientePaqueteDto = new ClientePaqueteDto();
        this.usuarioDto = new UsuarioDto();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ClientePaqueteDto getClientePaqueteDto() {
        return clientePaqueteDto;
    }

    public void setClientePaqueteDto(ClientePaqueteDto clientePaqueteDto) {
        this.clientePaqueteDto = clientePaqueteDto;
    }

    public UsuarioDto getUsuarioDto() {
        return usuarioDto;
    }

    public void setUsuarioDto(UsuarioDto usuarioDto) {
        this.usuarioDto = usuarioDto;
    }

    public BigDecimal getValor() {
        return valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    public Date getFechaPago() {
        return fechaPago;
    }

    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

}
