package com.gimnasio.model;
// Generated ago 3, 2016 11:34:53 p.m. by Hibernate Tools 4.3.1
/**
 * DescuentoDto generated by hbm2java
 */
public class ProductoDto implements java.io.Serializable {

    private Integer id;
    private Integer id_producto;
    private String nombre;
    private Double precio;    
    private String pago;
    private Short tipo_pago;
    private Integer cantidad;
    
    public ProductoDto() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Double getPrecio() {
        return precio;
    }

    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    public Integer getCantidad() {
        return cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    public Integer getId_producto() {
        return id_producto;
    }

    public void setId_producto(Integer id_producto) {
        this.id_producto = id_producto;
    }

    public String getPago() {
        return pago;
    }

    public void setPago(String pago) {
        this.pago = pago;
    }

    public Short getTipo_pago() {
        return tipo_pago;
    }

    public void setTipo_pago(Short tipo_pago) {
        this.tipo_pago = tipo_pago;
    }        
}
