package com.gimnasio.model;
// Generated ago 3, 2016 11:34:53 p.m. by Hibernate Tools 4.3.1

/**
 * PaqueteDto generated by hbm2java
 */
public class PaqueteDto implements java.io.Serializable {

    private int id;
    private String nombre;
    private short tipo;
    private double precioBase;
    private short ynTiquetera;
    private short diasAplazamiento;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public double getPrecioBase() {
        return precioBase;
    }

    public void setPrecioBase(double precioBase) {
        this.precioBase = precioBase;
    }

    public short getYnTiquetera() {
        return ynTiquetera;
    }

    public void setYnTiquetera(short ynTiquetera) {
        this.ynTiquetera = ynTiquetera;
    }

    public short getDiasAplazamiento() {
        return diasAplazamiento;
    }

    public void setDiasAplazamiento(short diasAplazamiento) {
        this.diasAplazamiento = diasAplazamiento;
    }

    public short getTipo() {
        return tipo;
    }

    public void setTipo(short tipo) {
        this.tipo = tipo;
    }

}
