/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gimnasio.views;

import com.gimnasio.controller.Operaciones;
import com.gimnasio.model.ComboDto;
import com.gimnasio.model.ComboModel;
import com.gimnasio.model.MiRender;
import com.gimnasio.model.ProductoDto;
import com.gimnasio.model.TablaDto;
import com.gimnasio.model.TablaModelo;
import com.gimnasio.model.UsuarioDto;
import com.gimnasio.model.enums.ETipoPago;
import com.gimnasio.util.Util;
import java.awt.Font;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author rodolfo
 */
public class frmCafeteria extends javax.swing.JInternalFrame {

    private final ComboModel comboProductos;
    private final Operaciones operacion;
    private List<ProductoDto> listaProductos;
    private double precio;
    private ProductoDto productoDto;
    private UsuarioDto usuarioDto;
    private final String[] headTable;
    private final TablaModelo table;

    /**
     * Creates new form frmCafeteria
     *
     * @param operacion
     */
    public frmCafeteria(Operaciones operacion) {
        initComponents();
        this.productoDto = new ProductoDto();
        this.operacion = operacion;
        this.comboProductos = new ComboModel();

        this.comboProductos.getLista().clear();
        this.listaProductos = new ArrayList<>();
        
        Date date = new Date();
        this.txtFecha_inicio.setDate(date);
        
        this.headTable = new String[]{"Id", "Producto", "Cantidad", "Tipo", "Valor"};
        int widthColumna[] = {50, 200, 120, 120, 120};
        this.table = new TablaModelo(this.headTable);
        this.tblGastos.setModel(this.table);
        this.btnRecibo.setVisible(false);
        this.btnDelete.setVisible(false);
        
        try {
            
            this.listaProductos = this.operacion.getProductosDatosDto(null);
            ComboDto inicio = new ComboDto("", "-------------");
            this.comboProductos.getLista().add(0, inicio);
            
            this.comboProductos.getLista().addAll(this.operacion.getProductosDatosComboDto());
            this.cmbProducto.setModel(this.comboProductos);
        } catch (SQLException ex) {
            Logger.getLogger(frmCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            
            this.setConsultarTableDescuentos();
        } catch (SQLException ex) {
            Logger.getLogger(frmCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public final void setAsignarValores() {
        if (this.productoDto.getId_producto() != null && this.productoDto.getId_producto() > 0) {
            this.cmbProducto.setSelectedIndex(this.productoDto.getId_producto());
            this.cmbProducto.repaint();
        }
        
        this.txtCantidad.setText(String.valueOf(this.productoDto.getCantidad()));
        this.txtTotal_pagar.setText(String.valueOf(this.productoDto.getPrecio()));
       
        if (this.productoDto.getTipo_pago() == ETipoPago.EFECTIVO.getId() ) {                
            this.rbtEfectivo.setSelected(true);
        }

        if (this.productoDto.getTipo_pago() == ETipoPago.TARJETA.getId() ) {
            this.rbtTarjeta.setSelected(true);
        }

    }

    /**
     * 
     * @throws SQLException 
     */
    public void setConsultarTableDescuentos() throws SQLException {
        
        SimpleDateFormat data = new SimpleDateFormat("yyyy-MM-dd");
        String fechaInicio = data.format(this.txtFecha_inicio.getDate().getTime());
                    
        List<TablaDto> lista = this.operacion.getCafeteriaDatosTablaDto(fechaInicio);
        this.table.getData().clear();
        this.lblCantidad_descuentos.setText(String.valueOf(lista.size()));
        lista.stream().forEach((dto) -> {
            this.table.setAgregar(dto);
        });
        this.tblGastos.setDefaultRenderer(Object.class, new MiRender(this.table));
        this.tblGastos.repaint();
    }
    /**
     *
     */
    public void setLimpiar() {
        this.txtTotal_pagar.setText("");
        this.txtCantidad.setText("1");
        this.cmbProducto.setSelectedIndex(-1);
        this.cmbProducto.repaint();
        this.productoDto = new ProductoDto();
        this.btnRecibo.setVisible(false);
        this.btnDelete.setVisible(false);
    }

    ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmbProducto = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotal_pagar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblGenero = new javax.swing.JLabel();
        rbtEfectivo = new javax.swing.JRadioButton();
        rbtTarjeta = new javax.swing.JRadioButton();
        btnRecibo = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        lblCantidad_descuentos = new javax.swing.JLabel();
        txtFecha_inicio = new com.toedter.calendar.JDateChooser();
        lblFecha_nacimiento = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGastos = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAFETERIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SelectOpcion(evt);
            }
        });
        cmbProducto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cmbProductoPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Producto");

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setText("1");
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cantidad");

        txtTotal_pagar.setEditable(false);
        txtTotal_pagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal_pagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotal_pagarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total  a pagar");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/floppy-icon.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblGenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGenero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGenero.setText("Tipo pago");

        buttonGroup1.add(rbtEfectivo);
        rbtEfectivo.setSelected(true);
        rbtEfectivo.setText("Efectivo");
        rbtEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEfectivoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtTarjeta);
        rbtTarjeta.setText("Tarjeta");
        rbtTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTarjetaActionPerformed(evt);
            }
        });

        btnRecibo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/file-powerpoint-icon.png"))); // NOI18N
        btnRecibo.setText("Recibo");
        btnRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecibosetRegistrarPagoPlan(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/delete_icon.png"))); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletesetRegistrarPagoPlan(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal_pagar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtEfectivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtTarjeta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtEfectivo)
                    .addComponent(rbtTarjeta)
                    .addComponent(lblGenero))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE PRODUCTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 500));

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblResultado.setText("Resultados");

        lblCantidad_descuentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCantidad_descuentos.setText("0");

        txtFecha_inicio.setDateFormatString("yyyy-MM-dd");
        txtFecha_inicio.setMaxSelectableDate(new java.util.Date(253370786466000L));

        lblFecha_nacimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFecha_nacimiento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha_nacimiento.setText("Fecha Inicio");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gimnasio/files/Zoom-icon.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarsetConsultaClientes(evt);
            }
        });

        tblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGastossetEditarDescuento(evt);
            }
        });
        jScrollPane1.setViewportView(tblGastos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblResultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCantidad_descuentos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblFecha_nacimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblFecha_nacimiento))
                    .addComponent(txtFecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado)
                    .addComponent(lblCantidad_descuentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtTotal_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotal_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotal_pagarActionPerformed

    private void generarRecibo() {                                                                              
        Long id_cafeteria =  this.operacion.getLastIdCafeteria();
        String ruta = "cafeteria.jrxml";
        Map params = new HashMap<>();            
        params.put("ID_CLIENTE_PAQUETE", id_cafeteria.toString());                        
        Util.generarReportes(ruta, params);        
    } 
    
    private void generarRecibo_() {                                                                              
        Long id_cafeteria =  (long) this.productoDto.getId();
        String ruta = "cafeteria.jrxml";
        Map params = new HashMap<>();            
        params.put("ID_CLIENTE_PAQUETE", id_cafeteria.toString());                        
        Util.generarReportes(ruta, params);        
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (!this.txtCantidad.getText().equals("") && !this.txtTotal_pagar.getText().equals("") && this.cmbProducto.getSelectedItem() != null) {
            ComboDto select = (ComboDto) this.cmbProducto.getSelectedItem();
            int id = Integer.valueOf(select.getCodigo());
            int tipo_pago = 0;
            
            if (this.rbtEfectivo.isSelected()) {
                tipo_pago  = ETipoPago.EFECTIVO.getId();
            }
            
            if (this.rbtTarjeta.isSelected()) {
                 tipo_pago  = ETipoPago.TARJETA.getId();
            }
            
            int idRegistro = this.productoDto.getId() != null ? this.productoDto.getId()  : 0;
            
            boolean save = this.operacion.setSaveUpdateCafeteria(idRegistro, id, this.usuarioDto.getId(), this.txtCantidad.getText(), this.txtTotal_pagar.getText(), tipo_pago);
            if (save) {
                generarRecibo();
                try {                    
                    this.setConsultarTableDescuentos();
                } catch (SQLException ex) {
                    Logger.getLogger(frmCafeteria.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setLimpiar();
                /*
                JLabel label = new JLabel("<html>El pago para el producto: <b>" + select.getDescripcion() + "</b>, se guardó correctamente</html>");
                label.setFont(new Font("consolas", Font.PLAIN, 14));
                JOptionPane.showMessageDialog(this, label, "Información", JOptionPane.INFORMATION_MESSAGE);
                
                */
            }
        } else {
            JLabel label = new JLabel("Debe Selecionar un Producto y Cantidad");
            label.setFont(new Font("consolas", Font.PLAIN, 14));
            JOptionPane.showMessageDialog(this, label, "Mensaje de Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbProductoPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbProductoPopupMenuWillBecomeVisible
        // TODO add your handling code here
    }//GEN-LAST:event_cmbProductoPopupMenuWillBecomeVisible
    
    
    private void SelectOpcion(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SelectOpcion
        // TODO add your handling code here:    
        int id = 0;

        if (this.cmbProducto.getSelectedIndex() > -1) {
            ComboDto select = (ComboDto) this.cmbProducto.getSelectedItem();
            id = Integer.valueOf(select.getCodigo());
        }
        if (id > 0) {
            for (ProductoDto producto : this.listaProductos) {
                if (id == producto.getId()) {
                    this.precio = producto.getPrecio();
                    if (!this.txtCantidad.getText().equals("")) {
                        double valor = this.precio * Double.parseDouble(this.txtCantidad.getText());
                        this.txtTotal_pagar.setText(String.valueOf(valor));
                    }
                }
            }
        }
    }//GEN-LAST:event_SelectOpcion

    /**
     *
     * @param evt
     */
    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresa solo numeros", "Error de datos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    /**
     *
     * @param evt
     */
    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        // TODO add your handling code here:
        if (this.txtCantidad.getText().equals("") || Integer.valueOf(this.txtCantidad.getText()) < 1) {
            //JOptionPane.showMessageDialog(this, "este no es un valor valido", "Error de datos", JOptionPane.WARNING_MESSAGE);
            this.txtCantidad.setText("");
        } else {
            double valor = this.precio * Double.parseDouble(this.txtCantidad.getText());
            this.txtTotal_pagar.setText(String.valueOf(valor));
        }
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void rbtEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtEfectivoActionPerformed

    private void rbtTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtTarjetaActionPerformed

    private void tblGastossetEditarDescuento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGastossetEditarDescuento
        if (evt.getClickCount() == 2) {
            try {
                int fila = this.tblGastos.getSelectedRow();
                TablaDto dto = (TablaDto) this.table.getData().get(fila);
                this.productoDto = this.operacion.getCafeteriaDto(dto.getDato1());
                this.btnRecibo.setVisible(true);
                this.btnDelete.setVisible(true);
                setAsignarValores();
            } catch (SQLException ex) {
                Logger.getLogger(frmCafeteria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblGastossetEditarDescuento

    private void btnRecibosetRegistrarPagoPlan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecibosetRegistrarPagoPlan
        // TODO add your handling code here:
        this.generarRecibo_();
    }//GEN-LAST:event_btnRecibosetRegistrarPagoPlan

    private void btnBuscarsetConsultaClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarsetConsultaClientes
        try {
            //this.setConsultarTableClientes();
            this.setConsultarTableDescuentos();
        } catch (SQLException ex) {
            Logger.getLogger(frmCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_btnBuscarsetConsultaClientes

    /**
     * 
     * @param evt 
     */
    private void btnDeletesetRegistrarPagoPlan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletesetRegistrarPagoPlan
        // TODO add your handling code here:
        try {
            int option = JOptionPane.showConfirmDialog(null, "está a punto de eliminar este registro. ¿Desea continuar?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(option == JOptionPane.YES_OPTION) {
                boolean delete = false;
                String idProducto = String.valueOf(this.productoDto.getId());
                delete = this.operacion.deleteVenta(idProducto);
                if (delete) {
                    //this.gastoDto = new GastoDto();
                    this.setConsultarTableDescuentos();
                    this.setLimpiar();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmRegistrarPagos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeletesetRegistrarPagoPlan

    /**
     *
     * @param usuarioDto
     */
    public void setUsuarioDto(UsuarioDto usuarioDto) {
        this.usuarioDto = usuarioDto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRecibo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbProducto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad_descuentos;
    private javax.swing.JLabel lblFecha_nacimiento;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rbtEfectivo;
    private javax.swing.JRadioButton rbtTarjeta;
    private javax.swing.JTable tblGastos;
    private javax.swing.JTextField txtCantidad;
    private com.toedter.calendar.JDateChooser txtFecha_inicio;
    private javax.swing.JTextField txtTotal_pagar;
    // End of variables declaration//GEN-END:variables
}
